### ISSUE TITLE
NoSuchMethodError: Class 'String' has no instance method 'map'.

### ISSUE THREAD

**Issue by zirinisp** [Jaguar-dart/jaguar_serializer#115]
I followed the installation instruction and I am getting the following error when running `serializer build`

```
serializer build
Unhandled exception:
NoSuchMethodError: Class 'String' has no instance method 'map'.
Receiver: "lib/DataProvider/Firestore/Serializers/InstallationSerializer.dart"
Tried calling: map(Closure: (dynamic) => dynamic)
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      new InputSet (package:build_runner/src/generate/input_set.dart:21)
#2      apisPhase (package:jaguar_serializer_cli/src/phase/phase.dart:18)
#3      generatePhaseGroup (package:jaguar_serializer_cli/src/phase/phase.dart:23)
#4      phaseGroup (package:jaguar_serializer_cli/src/phase/phase.dart:56)
#5      build (package:jaguar_serializer_cli/src/generator.dart:30)
#6      start (package:jaguar_serializer_cli/src/generator.dart:67)
#7      main (file:///Users/zirinisp/.pub-cache/hosted/pub.dartlang.org/jaguar_serializer_cli-0.5.2/bin/serializer.dart:4)
#8      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

Any idea what might trigger it. I tried to copy paste your example and I am still getting the same error.

**Comment by zirinisp** [comment]
I have no idea, where I found the old instruction and I was sure that it was something simple that was causing the error that I was getting.

I managed to build and now everything is running fine.

Thank you very much for your help.
