### ISSUE TITLE
Serializer Cli with Uint8List failed in last version 

### ISSUE THREAD

**Issue by jaumard** [Jaguar-dart/jaguar_serializer#185]
I've update to serializer cli v2.2.8 and now Uint8list can't be generated correctly:

```
 JaguarCliException: Cannot handle Uint8List in UserUpdateSerializer!
[SEVERE] #0      AnnotationParser._expandTypeInfo (package:jaguar_serializer_cli/src/instantiater/instantiater.dart:441:5)
#1      AnnotationParser.parse (package:jaguar_serializer_cli/src/instantiater/instantiater.dart:94:20)
#2      JaguarSerializerGenerator.generateForAnnotatedElement (package:jaguar_serializer_cli/src/generator.dart:34:65)
#3      GeneratorForAnnotation.generate (package:source_gen/src/generator_for_annotation.dart:47:30)
<asynchronous suspension>
#4      _generate (package:source_gen/src/builder.dart:280:35)
<asynchronous suspension>
#5      _Builder._generateForLibrary (package:source_gen/src/builder.dart:73:15)
<asynchronous suspension>
#6      _Builder.build (package:source_gen/src/builder.dart:67:11)
<asynchronous suspension>
#7      runBuilder.buildForInput (package:build/src/generate/run_builder.dart:45:21)
<asynchronous suspension>
#8      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:29)
#9      ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#10     Future.wait (dart:async/future.dart:393:26)
#11     runBuilder.<anonymous closure> (package:build/src/generate/run_builder.dart:51:36)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _runZoned (dart:async/zone.dart:1516:10)
#15     runZoned (dart:async/zone.dart:1500:12)
#16     scopeLogAsync (package:build/src/builder/logging.dart:22:3)
#17     runBuilder (package:build/src/generate/run_builder.dart:51:9)
<asynchronous suspension>
#18     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:473:19)
#19     _NoOpBuilderActionTracker.trackStage (package:build_runner_core/src/generate/performance_tracker.dart:300:15)
#20     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:471:23)
<asynchronous suspension>
#21     NoOpTimeTracker.track (package:timing/src/timing.dart:222:44)
#22     _SingleBuild._runForInput.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:430:22)
#23     Pool.withResource (package:pool/pool.dart:127:28)
<asynchronous suspension>
#24     _SingleBuild._runForInput (package:build_runner_core/src/generate/build_impl.dart:426:17)
#25     _SingleBuild._runBuilder.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:374:38)
#26     MappedIterator.moveNext (dart:_internal/iterable.dart:393:18)
#27     Future.wait (dart:async/future.dart:393:26)
#28     _SingleBuild._runBuilder (package:build_runner_core/src/generate/build_impl.dart:373:36)
#29     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#30     _SingleBuild._runBuilder (package:build_runner_core/src/generate/build_impl.dart:371:40)
#31     _SingleBuild._runPhases.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:320:20)
#32     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#33     _rootRunUnary (dart:async/zone.dart:1132:38)
#34     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#35     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#36     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#37     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#38     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#39     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#40     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#41     _SingleBuild._matchingPrimaryInputs (package:build_runner_core/src/generate/build_impl.dart)
#42     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#43     _rootRunUnary (dart:async/zone.dart:1132:38)
#44     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#45     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#46     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#47     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#48     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#49     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#50     _rootRunUnary (dart:async/zone.dart:1132:38)
#51     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#52     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#53     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#54     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#55     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#56     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#57     _rootRun (dart:async/zone.dart:1124:13)
#58     _CustomZone.run (dart:async/zone.dart:1021:19)
#59     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#60     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#61     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#62     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#63     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#64     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

```

**Comment by tejainece** [comment]
I will fix this.
